name: CI

on: [push]

env:
  JAVA_OPTS: -Xmx3g -Xms64m

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - run: CALL gradlew.bat --no-daemon assemble check localPublishToBintrayIfRequiredOnCiReleaseTagNoPR -x jsBrowserTest
        shell: cmd
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}

  build-mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew --no-daemon assemble check localPublishToBintrayIfRequiredOnTravisReleaseTagNoPR -x jsBrowserTest
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}

  build-linux:
    needs: [build-windows, build-mac]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew --no-daemon assemble check lint testDebugUnitTest localPublishToBintrayIfRequiredOnTravisReleaseTagNoPR actuallyPublishBintrayIfOnTravisReleaseTagNoPR -x jsBrowserTest
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
